name: Build x64+aarch64

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
    - name: Build
      run: ./run.sh
